<a href="https://colab.research.google.com/github/sandymadrid/Datascience_Course/blob/master/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as ny

In [0]:
%%time
npoints = 100000000
points = ny.random.rand(npoints,2)
points_sqr = points ** 2
dfo = ny.sqrt(ny.sum(points_sqr,axis = 1))
outside_points = ny.sum(dfo > 1)
print("Area is ",(outside_points/npoints)*100)

Area is  21.462811000000002
CPU times: user 3.66 s, sys: 873 ms, total: 4.54 s
Wall time: 4.54 s


# Stats with numpy 


In [0]:
arr = ny.random.rand(1000)


In [0]:
hist_arr = ny.histogram(arr,bins = 3)
hist_arr[0]
ny.sum(hist_arr[0])

1000

In [0]:
arr1 = ny.random.randint(100,120,100)

arr2 = ny.random.randint(15,20,100)

arry_final = ny.vstack([arr1,arr2])

ny.min(arry_final,axis = 1)

# Problem


In [0]:
!cat cric_data.tsv | head -15

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216
9	85	12	224
10	18	63	161
11	4	107	276
12	7	76	283
13	37	4	297


In [0]:
import numpy as np

cric_data = np.loadtxt('cric_data.tsv',skiprows=1,usecols = (1,2,3))

print(cric_data)

In [0]:
mean = np.mean(cric_data,axis=0)
median = np.median(cric_data,axis = 0 )
perc_25_50 = np.percentile(cric_data,(25,75),axis = 0)
iqr = perc_25_50[1] - perc_25_50[0]

print('Mean:',mean,' Median',median,'IQR',iqr,sep= '\n')

Mean:
[ 39.87555556  32.06222222 220.79555556]
 Median
[ 27.  22. 216.]
IQR
[57. 46. 98.]


In [0]:
np.histogram(cric_data[:,0],bins = 10)


(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [0]:
sachin_25 = np.reshape(cric_data[:,0],(9,25))
np.mean(sachin_25,axis  = 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [0]:
sachin = cric_data[:,0]
rahul = cric_data[:,1]
india = cric_data[:,2]
np.mean(sachin[sachin >= 100])

125.0

In [0]:
np.mean(cric_data[cric_data[:,1] <=10,0])

40.2112676056338

In [0]:
qtrs = np.percentile(india,[25,50,75,100])
qtrs =qtrs.reshape(4,1)
indices = india < qtrs

for i in range(4):
  print(i,np.mean(sachin[indices[i,:]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


In [0]:
sr= cric_data[:,0:2]
np.argmax(sr,axis = 1)

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0])

In [133]:
a = np.array([1,2,3,4,5])
print(a[2:None])

[3 4 5]
